# Default values for go-filecoin-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
domain: stats.nerpa.fildev.network
domainInternal: stats-internal.nerpa.fildev.network
htpasswd: protocol:$apr1$IWwZ.TPe$esqo2KqTYQRagnQRk.xvx0
metricsRange: 30m
metricsRefresh: 25s
grafana:
  image:
    repository: 657871693752.dkr.ecr.us-east-1.amazonaws.com/lotus-grafana
    tag: v1.9
  sidecar:
    datasources:
      enabled: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard-resize
    accessModes: ["ReadWriteOnce"]
    size: 15Gi
  service:
    type: LoadBalancer
    port: 443
    portName: https
    targetPort: 8000
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:657871693752:certificate/758a00d5-1004-4075-85cd-7037c3300270"
      external-dns.alpha.kubernetes.io/hostname: stats.nerpa.fildev.network,stats-internal.nerpa.fildev.network
      external-dns.alpha.kubernetes.io/alias: "true"
      external-dns.alpha.kubernetes.io/ttl: "60"
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
  nodeSelector:
    monitoring: "true"
  env:
    GF_AUTH_DISABLE_LOGIN_FORM: "false"
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
    GF_AUTH_BASIC_ENABLED: "false"
    GF_SMTP_ENABLED: "true"
    GF_SMTP_HOST: "smtp.mailgun.org:587"
    GF_SMTP_FROM_ADDRESS: "no-reply@mg.kittyhawk.wtf"
    GF_SMTP_FROM_NAME: "Lotus Grafana Admin"
  extraContainers:
    - name: nginx
      image: bitnami/nginx:1.16
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: config-volume
          mountPath: /opt/bitnami/nginx/conf/server_blocks
          readOnly: true
        - name: htpasswd
          mountPath: /opt/bitnami/nginx/htpasswd
          readOnly: true
  extraConfigmapMounts:
    - name: config-volume
      mountPath: /opt/bitnami/nginx/conf/server_blocks
      configMap: nerpanet-grafana-nginx-sidecar
      readOnly: true
    - name: htpasswd
      mountPath: /opt/bitnami/nginx/htpasswd
      configMap: nerpanet-grafana-nginx-htpasswd
      readOnly: true
  smtp:
    existingSecret: mailgun
