image:
  tag: mainnet-v1.16.0

prometheusOperatorServiceMonitor: true

secrets:
  jwt:
    enabled: true
    secretName: lotus-jwt

resources:
  requests:
    memory: 150Gi

nodeSelector:
  "fil-infra.protocol.ai/node-type": "lotus-high-memory"

importSnapshot:
  enabled: true
  strategy: url
  url: https://snapshots.mainnet.fildevops.net/minimal/latest

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  network: mainnet

persistence:
  datastore:
    enabled: true
    easyReset: true
    storageClassName: "gp2"
    size: "2000Gi"
