---
- name: Add telegraf apt key
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"

- name: Add telegraf apt repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu disco stable"
    state: present

- name: Update repositories cache and install "telegraf" package
  apt:
    name: telegraf
    update_cache: yes

- name: Ensure telegraf started and enabled
  systemd:
    name: telegraf
    enabled: yes

- name: Copy telegraf configuration template to hosts
  template:
    src: templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: '0644'
