---
all:
  vars:
    ssh_keys_access:
      - filecoin
      - cory
      - ognots
      - travisperson
      - kubuxu
      - magik6k
      - whyrusleeping
      - whysosirius
      - vyzo
      - aayush
      - mg
      - anorth
      - stebalien
      - raulk
      - jennifer
      - circleci
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            preminer-0.interop.fildev.network:
        preminer1:
          hosts:
            preminer-1.interop.fildev.network:
        preminer2:
          hosts:
            preminer-2.interop.fildev.network:
        preminer3:
          hosts:
            preminer-3.interop.fildev.network:
        preminer4:
          hosts:
            preminer-4.interop.fildev.network:
        preminer5:
          hosts:
            preminer-5.interop.fildev.network:
        bootstrap0:
          hosts:
            bootstrap-0.interop.fildev.network:
        bootstrap1:
          hosts:
            bootstrap-1.interop.fildev.network:
        toolshed0:
          hosts:
            toolshed-0.interop.fildev.network:
        toolshed1:
          hosts:
            toolshed-1.interop.fildev.network:
        scratch0:
          hosts:
            scratch-0.interop.fildev.network:
        scratch1:
          hosts:
            scratch-1.interop.fildev.network:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    t01002:
      children:
        preminer2:

    t01003:
      children:
        preminer3:

    t01004:
      children:
        preminer4:

    t01005:
      children:
        preminer5:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        toolbox:
        scratch:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:
        t01003:
        t01004:
        t01005:

    toolbox:
      children:
        toolbox0:
        toolbox1:

    faucet:
      children:
        toolshed0:

    stats:
      children:
        toolshed0:

    preminer:
      children:
        t01000:
        t01001:
        t01002:
        t01003:
        t01004:
        t01005:

    bootstrap:
      children:
        bootstrap0:
        bootstrap1:

    scratch:
      children:
        scratch0:
        scratch1:
