image:
  tag: mainnet-v1.13.0

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 32Gi
    cpu: 4
  limits:
    memory: 48Gi
    cpu: 6

importSnapshot:
  enabled: true
  claimName: chain-exports
  network: mainnet
  exportRelease: finality-stateroots
  exitCodeOnMissing: 1

persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "2000Gi"
    storageClassName: "gp2"

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1

disputer:
  enabled: yes
  walletAddr: f1tq6t4t5qrlosirgoweyb3lgrdwa3zspixwukbfa
  env:
    - name: GOLOG_LOG_FMT
      value: json

additionalLabels:
  network: mainnet
