image:
  tag: mainnet-v1.5.3

resources:
  requests:
    memory: 96Gi
    cpu: 8
  limits:
    memory: 112Gi
    cpu: 16

importSnapshot:
  enabled: false
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1
  - name: DISABLE_PRE_MIGRATIONS
    value: "1"

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  mode: open
  network: mainnet

persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "8000Gi"
