image:
  tag: v1.2.0

resources:
  requests:
    memory: 96Gi
    cpu: 8
  limits:
    memory: 112Gi
    cpu: 16

importSnapshot:
  enabled: false
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  mode: open
  network: mainnet

nodeSelector:
  mode: restricted

persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "2000Gi"
