image:
  tag: mainnet-v1.5.0

secrets:
  libp2p:
    enabled: true
    secretName: fullnode-7-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-7-jwt-secrets

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1

importSnapshot:
  enabled: true
  claimName: chain-exports
  network: mainnet
  exportRelease: finality-stateroots
  exitCodeOnMissing: 1
