image:
  tag: mainnet-b872cb26d

secrets:
  libp2p:
    enabled: true
    secretName: fullnode-1-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-1-jwt-secrets
persistence:
  datastore:
    size: "6000Gi"
