secrets:
  libp2p:
    enabled: true
    secretName: disputer-1-libp2p-secrets
  jwt:
    enabled: true
    secretName: disputer-1-jwt-secrets
  wallets:
    enabled: true
    secretName: wallet-disputer-1
loadBalancer:
  enabled: false
