image:
  tag: v1.20.3-rpc-p01-hf02 # {"$imagepolicy": "ntwk-mainnet:lotus-latest-release:tag"}

lotus:
  image: docker.io/filecoin/lotus-all-in-one:v1.20.3-rpc-p01-hf02 # {"$imagepolicy": "ntwk-mainnet:lotus-latest-release"}
