secrets:
  libp2p:
    enabled: true
    secretName: fullnode-2-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-2-jwt-secrets

importSnapshot:
  enabled: false
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0