---
deployments:
  # efs access
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-mainnet-fullnode
    name: efs-access
    values:
      - efs-access
  # # fullnode volume snapshot
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-0-lotus-0
  #   values:
  #     - base
  #     - fullnode-0
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-1-lotus-0
  #   values:
  #     - base
  #     - fullnode-1
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-2-lotus-0
  #   values:
  #     - base
  #     - fullnode-2
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-3-lotus-0
  #   values:
  #     - base
  #     - fullnode-3
  # fullnodes
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-0
    values:
      - base
      - fullnode-0
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-1
    values:
      - base
      - fullnode-1
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-2
    values:
      - base
      - fullnode-2
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-3
    values:
      - base
      - fullnode-3
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-4
    values:
      - base
      - fullnode-4
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-5
    values:
      - base
      - fullnode-5
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-6
    values:
      - base
      - fullnode-6
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-7
    values:
      - base
      - fullnode-7
  # consensus check
  - chart: filecoin/lotus-consensus-check
    version: 0.1.1
    namespace: ntwk-mainnet-fullnode
    name: cc-common
    values:
      - cc-common
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.1
    namespace: ntwk-calibnet-fullnode
    name: fullnode-0
    values:
      - base
      - fullnode-0
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.1
    namespace: ntwk-calibnet-fullnode
    name: fullnode-1
    values:
      - base
      - fullnode-1
