---
deployments:
  # efs access
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-mainnet-fullnode
    name: efs-access
    values:
      - efs-access
  # # fullnode volume snapshot
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-0-lotus-0
  #   values:
  #     - base
  #     - fullnode-0
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-1-lotus-0
  #   values:
  #     - base
  #     - fullnode-1
  # - chart: filecoin/volume-snapshotter
  #   version: 0.1.0
  #   namespace: ntwk-mainnet-fullnode
  #   name: vsnap-datastore-volume-fullnode-2-lotus-0
  #   values:
  #     - base
  #     - fullnode-2
  # fullnodes
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-0
    values:
      - base
      - fullnode-0
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-1
    values:
      - base
      - fullnode-1
  - chart: filecoin/lotus-fullnode
    version: 0.2.0
    namespace: ntwk-mainnet-fullnode
    name: fullnode-2
    values:
      - base
      - fullnode-2
  - chart: filecoin/lotus-fullnode
    version: 0.3.2
    namespace: ntwk-mainnet-fullnode
    name: fullnode-7
    values:
      - base
      - fullnode-7
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-calibnet-fullnode
    name: fullnode-0
    values:
      - base
      - fullnode-0
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-calibnet-fullnode
    name: fullnode-1
    values:
      - base
      - fullnode-1
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-calibnet-fullnode
    name: disputer-0
    values:
      - base
      - disputer-0
  # dealbot nerpanet
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-nerpanet-dealbot
    name: efs-access
    values:
      - efs-access
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-nerpanet-dealbot
    name: dealbot-fullnode-0
    values:
      - base
      - dealbot-fullnode-0
  - chart: runix/pgadmin4
    version: 1.6.1
    namespace: ntwk-nerpanet-dealbot
    name: pgadmin
    values:
      - base
  # gateway
  - chart: filecoin/lotus-gateway
    version: 0.1.5
    namespace: ntwk-mainnet-fullnode
    name: gateway-0
    values:
      - base
      - gateway-0
  # splitstore testing
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-mainnet-splitstore-test
    name: standard-16g
    values:
      - base
      - limits-16G
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-mainnet-splitstore-test
    name: standard-32g
    values:
      - base
      - limits-32G
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-mainnet-splitstore-test
    name: standard-48g
    values:
      - base
      - limits-48G
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-mainnet-splitstore-test
    name: splitstore-16g
    values:
      - base
      - coldstore-discard
      - limits-16G
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-mainnet-splitstore-test
    name: splitstore-32g
    values:
      - base
      - coldstore-discard
      - limits-32G
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-mainnet-splitstore-test
    name: splitstore-48g
    values:
      - base
      - coldstore-discard
      - limits-48G
  - chart: filecoin/lotus-bundle
    namespace: ntwk-mainnet-storetheindex
    name: storetheindex-0
    values:
      - base
      - storetheindex-0
