apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - fullnode-helmrelease-patch.yaml

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: fullnode-network-common
