apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/storage/
- ../../../base/monitoring/
- ../mainnet/cluster
- ../calibrationnet/cluster
- flux-slack-url.yaml

patches:
- patch: |
    apiVersion: notification.toolkit.fluxcd.io/v1beta1
    kind: Alert
    metadata:
      name: slack-alerts
    spec:
      summary: "prod/ap-southeast-1"
  target:
    group: notification.toolkit.fluxcd.io
    version: v1beta1
    kind: Alert
    name: slack-alerts
