---
lotus_libp2p_keyinfo: "{{ libp2p_keyinfo }}"
lotus_libp2p_address: "{{ libp2p_address }}"
lotus_libp2p_port: 1347
lotus_path: "/var/lib/lotus"
lotus_golog_file: "/var/log/lotus.log"
lotus_proof_params_path: "/var/tmp/filecoin-proof-parameters"
lotus_systemd_extras:
  MemoryHigh: 12G
  MemoryMax: 16G
  LimitNOFILE: 32768
