chainwatch_golog_file: "/var/log/chainwatch.log"
chainwatch_db: "postgres://postgres:{{ vault_chainwatch_db_password }}@terraform-20200422195843014000000001.chbzkiyxnqef.us-west-2.rds.amazonaws.com:5432/{{ network_name }}?sslmode=disable"

