apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
spec:
  install:
    timeout: 120m
    remediation:
      retries: 100
  upgrade:
    timeout: 120m
    remediation:
      retries: 100
  chart:
    spec:
      chart: lotus-bundle
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: filecoin-project-charts
      version: 0.0.18
  interval: 1m0s
  # The values are merged in the order given, with the later values overwriting earlier. These values always have a lower priority 
  valuesFrom:
  - kind: ConfigMap
    name: gateway-common-values
