image:
  tag: mainnet-v1.16.0

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 48Gi
    cpu: 6 
  limits:
    memory: 48Gi
    cpu: 6

importSnapshot:
  enabled: true
  strategy: url
  claimName: chain-exports
  network: mainnet
  exportRelease: finality-stateroots
  exitCodeOnMissing: 1

persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "2000Gi"
    storageClassName: "gp2"

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1

disputer:
  enabled: true
  walletAddr: f1xfr2bh23j2s7rmvwxx4linma4luxqxpyrfax5da
  # maxFee:
  env:
    - name: GOLOG_LOG_FMT
      value: json

additionalLabels:
  network: mainnet

persistence:
  datastore:
    enabled: true
    size: "16000Gi"
