---
all:
  vars:
    ssh_keys_access:
      - filecoin
      - cory
      - ognots
      - travisperson
      - kubuxu
      - magik6k
      - whyrusleeping
      - whysosirius
      - vyzo
      - aayush
      - mg
      - anorth
      - stebalien
      - jennifer
      - geoff-vball
      - circleci
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            preminer-0.calibration.fildev.network:
        preminer1:
          hosts:
            preminer-1.calibration.fildev.network:
        preminer2:
          hosts:
            preminer-2.calibration.fildev.network:
        bootstrap0:
          hosts:
            bootstrap-0.calibration.fildev.network:
        bootstrap1:
          hosts:
            bootstrap-1.calibration.fildev.network:
        bootstrap2:
          hosts:
            bootstrap-2.calibration.fildev.network:
        bootstrap3:
          hosts:
            bootstrap-3.calibration.fildev.network:
        toolshed0:
          hosts:
            toolshed-0.calibration.fildev.network:
        toolshed1:
          hosts:
            toolshed-1.calibration.fildev.network:
        scratch0:
          hosts:
            scratch-0.calibration.fildev.network:
        scratch1:
          hosts:
            scratch-1.calibration.fildev.network:

    canary:
      children:
        bootstrap0:
        preminer0:
        scratch0:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    t01002:
      children:
        preminer2:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        faucet:
        stats:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:

    toolbox:
      children:
        faucet:
        stats:

    faucet:
      children:
        toolshed0:

    stats:
      children:
        toolshed1:

    preminer:
      children:
        t01000:
        t01001:
        t01002:

    bootstrap:
      children:
        bootstrap0:
        bootstrap1:
        bootstrap2:
        bootstrap3:

    scratch:
      children:
        scratch0:
        scratch1:
