apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: lotus-latest-release
spec:
  policy:
    semver:
      range: '~1.x'
  imageRepositoryRef:
    name: filecoin-lotus-all-in-one
---
