# Default values for filecoin dealbot
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
logLevel: info
image:
  repo: filecoin/dealbot
  tag: "latest" # required
  pullPolicy: Always

# Custom labels
#labels:
  #name: foo

# prometheus service monitor
prometheusOperatorServiceMonitor: false
prometheusPort: ":9991"

logLevel: error
#logFormat: json
#logLevelNamed: "vm:error,badgerbs:error"

jaeger:
  enabled: false
  host: ""
  port: 6831
  serviceName: "dealbot"
  sampler:
    type: "probabilistic"
    param: 0.0001
