controller: 
  enabled: true
  postgres:
    enabled: true
  ingress:
    enabled: true
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-realm: Filecoin Infrastructure Team
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-secret-type: auth-file
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: lb.mainnet-us-east-1.filops.net
        paths:
         - path: /mainnet-dealbot-controller(/|$)(.*)
  services:
    api:
      annotations: {}
    graphql:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: dealbot-mainnet.mainnet-us-east-1.filops.net
  secrets:
    keySecret: dealbot-controller-key
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi

postgres:
  enabled: true
  instances: 1
  version: 13
  teamid: dealbotteam
  user: dealbotuser
  database: dealbotdb
  volume: 100Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi
  env:
    - name: DEALBOT_BASICAUTH
      valueFrom:
        secretKeyRef:
          name: basic-auth-plain
          key: auth


daemon:
  enabled: true
  replicas: 1
  lotusAPI:
    lotusAPITokenSecret: "fullnode-0-jwt-secrets"
    lotusAPIMultiaddr: "/dns/dealbot-fullnode-0-lotus-daemon/tcp/1234/p2p/12D3KooWFX36AfFhL6949FDDjHDW7VJsr1f19brTrZxHBCz28ks2"
    wallet: f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq
  persistence:
    enabled: true
    claimName: chain-exports
    mountPath: /efs
    data: /efs/dealbot/mainnet/nodedata
    nodedata: /efs/dealbot/mainnet/nodedata
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
  env:
    - name: DEALBOT_ID
      value: daemon-verified-0
    - name: DEALBOT_TAGS
      value: verified
