image:
  tag: mainnet-v1.18.0

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 32Gi
    cpu: 4
  limits:
    memory: 48Gi
    cpu: 6

importSnapshot:
  enabled: true
  strategy: url

persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "16000Gi"
    storageClassName: "gp2"

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1

disputer:
  enabled: true
  walletAddr: f1tq6t4t5qrlosirgoweyb3lgrdwa3zspixwukbfa
  # maxFee:
  env:
    - name: GOLOG_LOG_FMT
      value: json

additionalLabels:
  network: mainnet

persistence:
  datastore:
    enabled: true
    size: "2000Gi"
